### PR TITLE
update readme file

### PR DESCRIPTION
**Pull request by nils-hoyer**
fix wrong command example from android to ios

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
👍

**Comment by christian-bromann** [comment]
@nils-hoyer mind signing the CLA?

**Comment by kopax-polyconseil** [comment]
I think this CLA Authorization is slowing the process for merging stuff and should be removed. An Open PR is already an agreement to your contribution guideline. Lets just remove this (bad) good idea and speedup the whole process. :)

**Review by kopax-polyconseil — APPROVED** [review]

**Comment by christian-bromann** [comment]
@kopax-polyconseil the CLA is important as this project is part of the OpenJS Foundation. It just needs to be set up once and i rarely have issues like these. An option would be to switch to an DCO but that has its own challenges.

**Pull request closed without merging**
